version: "3.8"

services:
  app:
    build:
      context: ../..
      dockerfile: ./docker/dev/app/Dockerfile
    container_name: fastify-app
    ports:
      - 3000:3000
    env_file:
      - "../../.env.local"
    restart: always
    tty: true
